version: '3.8'
services:
  rest-api:
    build: .
    ports:
      - '3000:3000'
    hostname: listwibuku-rest-service
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: pgpassword
      DB_HOST: listwibuku-rest-database
      DB_PORT: 5433
      PORT: 3000
  postgresql:
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    hostname: listwibuku-rest-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpassword}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
volumes:
  postgres:
