POST http://localhost:8000/bookings
Content-Type: application/json

{
  "id": 2
}

###

POST http://localhost:8000/bookings/webhook
Content-Type: application/json

{"failReason":"","invoiceId":"655dcc1f2ec674a837a7f2b1","status":"success"}

###

POST http://localhost:8000/bookings/cancel
Content-Type: application/json

{
  "id": 25
}

###

GET http://localhost:8000/bookings/26
Accept: application/json

###

GET http://localhost:8000/bookings/23/print

###

GET http://localhost:8000/bookings?ids=23&ids=24&ids=25
