POST http://localhost:8000/bookings
Content-Type: application/json

{
  "id": 1
}

###

POST http://localhost:8000/bookings/webhook
Content-Type: application/json

{"failReason":"","invoiceId":"655dcc1f2ec674a837a7f2b1","status":"success"}